export const StorageKeyItems = {
  LOGIN: 'login',
  PASSWORD: 'password',
  REFRESH_TOKEN: 'refreshToken',
  NEVER_ASK_AGAIN_CAMERA: 'neverAskAgainCamera',
  BIOMETRIC_KEY: 'USE_BIOMETRIC',
  PRIVATE_KEY: 'privateKey',
  SECRET_KEY_KEY: 'secret_key',
  IV_KEY: 'aes_iv',
  ACTIVE_KEY_VERSION: 'active_key_version',
  KEY_PREFIX: 'crypto_key_',
  KEY_STORAGE_PREFIX: 'crypto_key_',
  IV_STORAGE_PREFIX: 'crypto_iv_',
  ACTIVE_KEY_ID: 'crypto_active_key_id',
  LAST_ROTATION_KEY: 'crypto_last_rotation',
  SECRET_KEY_PREFIX: 'crypto_key_',
  LEGACY_KEYS: 'crypto_legacy_keys',
  SESSION_KEY: 'user-session',
};
